title: Maxime Gallouin

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# White-listed plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  
 # This will require each of these gems automatically.
