include: ['.htaccess']

# White-listed plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  
 # This will require each of these gems automatically.

theme: jekyll-theme-minimal
